description = 'Host lists for common services in adblock and regex syntax.'

[postCSS]
  state = true

[head]
  responseHeaders = true

[banner]
  home = false
  section = false
  single = false

[sidebar]
  home = true
  section = true
  single = true

[breadcrumb]
  home = true
  homeIcon = 'file-spreadsheet'
  section = true
  single = true

[heading]
  home = false
  section = true
  single = true

[manifest]
  state = false

[copyright]
  link = 'https://aao.fyi/'
  year = '2023'

[robots]
  llmsTXT = true
